CREATE TABLE `Song`(
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Title` VARCHAR(255) NOT NULL,
    `Artist` VARCHAR(255) NOT NULL,
    `Album` VARCHAR(255) NOT NULL,
    `ReleaseDate` DATETIME NOT NULL,
    `Genre` VARCHAR(255) NOT NULL
);