// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _125_MusicLibraryWebApi.Data;

#nullable disable

namespace _125_MusicLibraryWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230818014057_AddOnModelCreating")]
    partial class AddOnModelCreating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_125_MusicLibraryWebApi.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Album = "Sea Change",
                            Artist = "Beck",
                            Genre = "Alternative",
                            ReleaseDate = new DateTime(2023, 8, 17, 21, 40, 57, 466, DateTimeKind.Local).AddTicks(5548),
                            Title = "The Golden Age"
                        },
                        new
                        {
                            Id = 5,
                            Album = "TestSea Change",
                            Artist = "TestBeck",
                            Genre = "TestAlternative",
                            ReleaseDate = new DateTime(2023, 8, 17, 21, 40, 57, 466, DateTimeKind.Local).AddTicks(5607),
                            Title = "TestTitle"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
